services:
  website:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: website
   ports:
     - '3333:3333'
   env_file:
     - .env
   restart: always 
  # live:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.live
  #   container_name: live
  #   depends_on:
  #    - website
  #   env_file:
  #     - .env
  #   restart: always